apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: my-kubernetes-secret
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: kvv2/webapp/config
        property: username
